# 서버 포트 설정
server:
  port: 8080

#database 연동 설정
spring:
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/board?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1234
  thymeleaf:
    cache: false
#  sql:
#    init:
#      mode: always # 서버 시작시 항상 classpath의 sql문을 실행하도록 설정
#      continue-on-error: true # 서버 시작시 sql문을 실행할 때 오류 무시하고 계속 진행
#      data-locations: data.sql # 서버 시작시 dml sql문을 실행할 위치 및 파일 지정

  #  spring data jpa 설정
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 
            client-secret: 
            scope:
              - email
              - profile
jwt:
  issuer: 
  secret-key: springboot-jwt
